# Stage 1: Builder
FROM node:20-alpine AS base

#START_ENV
ARG FE_ENV
ARG FE_PORT

ENV NEXT_NODE_ENV=${FE_ENV}
ENV NEXT_PORT_ENV=${FE_PORT}
#END_ENV

# STAGE 1: Builder
FROM base AS builder

WORKDIR /build

COPY package*.json ./
COPY apps/web/package*.json ./apps/web/
RUN npm install

# Copy project
COPY . .
ENV NODE_ENV=${NEXT_NODE_ENV}
RUN printenv
RUN npx turbo build --filter=./apps/web/

# STAGE 2: app
FROM base AS app
ENV NODE_ENV=${NEXT_NODE_ENV}

WORKDIR /app

COPY --from=builder ./build/apps/web/package*.json ./
# warning --production please use instead --omit=dev 
RUN npm install --omit=dev --force
COPY --from=builder ./build/apps/web/.next ./.next
COPY --from=builder ./build/apps/web/public ./public

# STAGE 3: Final Image (Run the app)
FROM base as final

WORKDIR /app-run

COPY --from=app ./app ./

EXPOSE ${NEXT_PORT_ENV}

CMD [ "npm", "start" ]
