name: "Build Web composite action"
description: "An example composite action that builds an Web image"
inputs:
  image:
    description: "Web Image Name"
    required: true
  push:
    description: "Push the image to the registry"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Echo all environment variable to apps/web
      shell: bash
      run: |
        printenv | grep -E '^(FE_ENV|FE_PORT)' >> apps/web/.env
        cat apps/web/.env

    - name: Docker Remove Image
      id: docker-remove-image
      shell: bash
      run: |
        sudo docker rmi -f ${{ inputs.image }} || true

    - name: Docker prune force
      id: docker-prune
      shell: bash
      run: |
        sudo docker system prune -a --volumes -f

    - name: Build Web
      id: build-web
      shell: bash
      run: |
        sudo docker build -f Dockerfile.Web \
        --build-arg FE_ENV=$FE_ENV \
        --build-arg FE_PORT=$FE_PORT \
        -t ${{ inputs.image }} .

    - name: Set image output
      shell: bash
      run: echo "image=${{ inputs.image }}" >> $GITHUB_ENV

    - name: Push Web
      if: ${{ inputs.push == 'true' }}
      shell: bash
      run: sudo docker push ${{ inputs.image }}
