name: "Build Web composite action"
description: "Builds a Web image and pushes to registry"
inputs:
  image:
    description: "Web Image Name"
    required: true
  push:
    description: "Push the image to the registry"
    required: false
    default: "true"
outputs:
  image:
    description: "The built image name"
    value: ${{ inputs.image }}
runs:
  using: "composite"
  steps:
    - name: Echo all environment variables to .env
      shell: bash
      run: |
        printenv | grep -E '^(FE_ENV|FE_PORT)' >> apps/web/.env
        cat apps/web/.env

    - name: Build Web
      id: build-web
      shell: bash
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        sudo docker build -f Dockerfile.Web \
        --build-arg FE_ENV=$FE_ENV \
        --build-arg FE_PORT=$FE_PORT \
        -t ${{ inputs.image }} .

    - name: Set image output
      shell: bash
      run: echo "image=${{ inputs.image }}" >> $GITHUB_ENV

    - name: Push Web
      if: ${{ inputs.push == 'true' }}
      shell: bash
      run: sudo docker push ${{ inputs.image }}
