name: 'Build Web composite action'
description: 'An example composite action that builds an Web image'
inputs:
  image:
    description: 'Web Image Name'
    required: true
  push:
    description: 'Push the image to the registry'
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Echo all environment variable to apps/web
      shell: bash
      run: |
        printenv | grep -E '^(NEXT_PUBLIC_NODE_ENV|TURBO_TOKEN|TURBO_TEAM|REDIS_URL|NEXT_PUBLIC_YTB_KEY|NEXT_PUBLIC_S3_DOMAIN)' >> apps/web/.env
        cat apps/web/.env

    - name: Build Web
      id: build-web
      shell: bash
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -f Dockerfile.Web \
        --build-arg NEXT_PUBLIC_NODE_ENV=$NEXT_PUBLIC_NODE_ENV \
        --build-arg TURBO_TOKEN=$TURBO_TOKEN \
        --build-arg TURBO_TEAM=$TURBO_TEAM \
        --build-arg REDIS_URL=$REDIS_URL \
        --build-arg NEXT_PUBLIC_YTB_KEY=$NEXT_PUBLIC_YTB_KEY \
        --build-arg NEXT_PUBLIC_S3_DOMAIN=$NEXT_PUBLIC_S3_DOMAIN \
        --build-arg NEXT_PUBLIC_RECAPTCHA_SITE_KEY=$NEXT_PUBLIC_RECAPTCHA_SITE_KEY \
        -t ${{ inputs.image }} .

    - name: Push Web
      if: ${{ inputs.push == 'true' }}
      shell: bash
      run: docker push ${{ inputs.image }}
