name: 'Configure AWS credentials'
description: 'Configure AWS credentials for Amazon ECR login'

runs:
  using: "composite"
  steps:

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: $AWS_DEPLOY_ACCESS_KEY_ID
        aws-secret-access-key: $AWS_DEPLOY_SECRET_ACCESS_KEY
        aws-region: $AWS_REGION

    - name: Login to Amazon ECR
      run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      shell: bash



