name: Deploy to Amazon ECS

on:
  push:
    branches:
      - integrate-ecs

env:
  AWS_REGION: ap-southeast-1
  ECR_REGISTRY: 739275471493.dkr.ecr.ap-southeast-1.amazonaws.com
  WEB_IMAGE: fe-monostack

permissions:
  contents: read

jobs:
  aws-config:
    name: Configure AWS credentials
    runs-on: self-hosted
    steps:
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

  build-web:
    name: Build Web
    runs-on: self-hosted
    outputs:
      image: ${{ steps.build-build-web.outputs.image }}
    needs: [aws-config]
    steps:
      - uses: actions/checkout@v2
      - name: Build Web
        id: build-web
        uses: ./.github/actions/build-web
        with:
          image: "${{ env.WEB_IMAGE }}:${{ github.sha }}"
          deploy_env: integrate
